# Generated by Django 4.0.4 on 2022-06-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0003_categoria_alter_blog_image_alter_blog_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='categoria',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
