# Generated by Django 4.0.4 on 2022-06-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0009_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='Confirmar_traferencia'),
        ),
    ]
