# Generated by Django 4.0.4 on 2022-06-22 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0010_alter_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='user',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
