# Generated by Django 4.0.4 on 2022-06-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0018_alter_blog_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='categoria',
            field=models.CharField(choices=[('cacho', 'cacho'), ('toams', 'toams'), ('asdassd', 'asdassd'), ('tomisdds', 'tomisdds'), ('eryhtfhjnvc', 'eryhtfhjnvc')], max_length=50),
        ),
    ]
