# Generated by Django 4.0.4 on 2022-06-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0024_rename_snipper_blog_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='snippet',
            field=models.TextField(default='Click link above to read blog....', max_length=50),
        ),
    ]
