# Generated by Django 4.0.4 on 2022-06-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0033_alter_blog_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='categoria',
            field=models.CharField(default='Sin categoria', max_length=50),
        ),
    ]
