# Generated by Django 4.0.4 on 2022-06-25 14:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BlogApp', '0035_alter_blog_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='like',
            field=models.ManyToManyField(null=True, related_name='Blog_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
